### PR TITLE
chore: Fix cargo-deny configuration

### PR DESCRIPTION
**Pull request by DataTriny**
Blocks #7 

This makes cargo-deny stricter, but also more in line with the rest of the ecosystem.

### CODE REVIEW

**Comment by mwcampbell** [comment]
How much of this will we be applying to the main repo? Of course, this is the kind of thing that's annoying to maintain across multiple repos. But I think we had to do that split.

**Comment by DataTriny** [comment]
@mwcampbell I plan to basically copy this into the main repo, which will fix https://github.com/AccessKit/accesskit/issues/349. We will be able to clean deny.toml a bit once https://github.com/AccessKit/accesskit/pull/456 lands.

**Comment by DataTriny** [comment]
So it would make more sense  to merge the zbus 4 PR first.

**Comment by DataTriny** [comment]
Here is the reason for the skipped dependencies:

- event-listener and event-listener-strategy: old async-channel version,
- syn: old thiserror version

In all cases we could get rid of them by updating the old crates in Cargo.lock.

**Comment by DataTriny** [comment]
This should be ready now.

**Pull request merged**
